openapi: 3.0.0
info:
  title: My Portfolio API
  description: My Portfolio API documentation with OpenAPI YAML file.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /projects/{id}:
    get:
      tags:
        - projects
      summary: Get project by ID
      operationId: getProjectById
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: ID of the project to retrieve
      responses:
        '200':
          description: project found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDto'
        '404':
          description: Project not found

  /projects/summary:
    get:
      tags:
        - projects
      summary: Get projects summaries
      operationId: getProjectsSummaries
      responses:
        '200':
          description: List of projects summaries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectSummaryDto'
        '404':
          description: Project not found

components:
  schemas:
    ProjectDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    SkillDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        version:
          type: string
        category:
          type: string
        active:
          type: boolean
    ProjectSkillDto:
      type: object
      properties:
        skill:
          $ref: '#/components/schemas/SkillDto'
        skillPriority:
          type: integer
          format: int64
        usagePercentage:
          type: number
    ProjectSummaryDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        logoUrl:
          type: string
        title:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        summary:
          type: string
        topSkills:
          type: array
          items:
            $ref: '#/components/schemas/ProjectSkillDto'