openapi: 3.0.0
info:
  title: My Portfolio API
  description: My Portfolio API documentation with OpenAPI YAML file.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /projects/{id}:
    get:
      summary: Get project by ID
      operationId: getProjectById
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: ID of the project to retrieve
      responses:
        '200':
          description: project found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDto'
        '404':
          description: Project not found

components:
  schemas:
    ProjectDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string